version: '3'

services:
  accounts_test:
    build:
      context: ./accounts
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - geth_test
    volumes:
      - ./accounts/src:/app/src
      - ./accounts/config:/app/config
      - ./accounts/.babelrc:/app/.babelrc
    environment:
      NODE_ENV: test
      BLOCKCHAIN_HOST: http://geth_test
      BLOCKCHAIN_PORT: 8546
    networks:
      - test_net

  api-gateway_test:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    restart: on-failure
    volumes:
      - ./api-gateway/src:/app/src
      - ./api-gateway/config:/app/config
      - ./api-gateway/.babelrc:/app/.babelrc
    environment:
      NODE_ENV: test
      ACCOUNTS_HOST: http://accounts_test
      ACCOUNTS_PORT: 80
      ZKP_HOST: http://zkp_test
      ZKP_PORT: 80
      DATABASE_HOST: http://database_test
      DATABASE_PORT: 80
      OFFCHAIN_HOST: http://offchain_test
      OFFCHAIN_PORT: 80
    ports:
      - "8001:80"
    networks:
      - test_net

  offchain_test:
    build:
      context: ./offchain
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - geth_test
    volumes:
      - ./offchain/src:/app/src
      - ./offchain/build-test:/app/build
      - ./offchain/.babelrc:/app/.babelrc
      - ./zkp-utils:/app/node_modules/zkp-utils
      - ./offchain/config:/app/config
    environment:
      NODE_ENV: test
      AUTHENTICATION_API_HOST: http://api-gateway_test
      AUTHENTICATION_API_PORT: 80
      BLOCKCHAIN_HOST: http://geth_test
      BLOCKCHAIN_PORT: 8545
    networks:
      - test_net

  zkp_test:
    build:
      context: ./zkp
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - geth_test
    volumes:
      - ./zkp/src:/app/src
      - ./zkp/build-test:/app/build
      - ./zkp/code:/app/code
      - ./zkp/.babelrc:/app/.babelrc
      - ./zkp-utils:/app/node_modules/zkp-utils
      - ./zkp/config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      NODE_ENV: test
      BLOCKCHAIN_HOST: http://geth_test
      BLOCKCHAIN_PORT: 8545
      ZKP_CODE_VOLUME: nightfall_zkp_code_test
    networks:
      - test_net

  # ganache_test:
  #   image: trufflesuite/ganache-cli:latest
  #   command: ganache-cli --accounts=10 --defaultBalanceEther=1000
  #   ports:
  #     - "8546:8545"
  #   networks:
  #     - test_net

  geth_test:
    image: ethereum/client-go:stable #https://github.com/ethereum/go-ethereum/issues/19427#issuecomment-481680245
    command:
      --syncmode "light"
      --testnet
      --rpc
      --rpcaddr "0.0.0.0"
      --rpccorsdomain "*"
      --rpcvhosts "*"
      --rpcapi db,eth,net,web3,personal,shh
      --ws
      --wsaddr "0.0.0.0"
      --wsorigins "*"
      --wsapi db,eth,net,web3,personal,shh
      --shh
      --cache 1024
      --allow-insecure-unlock
      # --bootnodes "enode://20c9ad97c081d63397d7b685a412227a40e23c8bdc6688c6f37e97cfbc22d2b4d1db1510d8f61e6a8866ad7f0e17c02b14182d37ea7c3c8b9c2683aeb6b733a1@52.169.14.227:30303,enode://6ce05930c72abc632c58e2e4324f7c7ea478cec0ed4fa2528982cf34483094e9cbc9216e7aa349691242576d552a2a56aaeae426c5303ded677ce455ba1acd9d@13.84.180.240:30303"
    volumes:
      - ~/.ethereum:/root/.ethereum:delegated
    ports:
      - "30303:30303"
      - "30304:30304"
      - "8545:8545" # http
      - "8546:8546" # ws
    networks:
      - test_net

  database_test:
    build:
      context: ./database
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - mongo_test
    volumes:
      - ./database/src:/app/src
      - ./database/.babelrc:/app/.babelrc
      - ./zkp-utils:/app/node_modules/zkp-utils
      - ./database/config:/app/config
      - ./database/setup-mongo-acl-for-new-users.js:/app/setup-mongo-acl-for-new-users.js
    environment:
      - NODE_ENV=test
    networks:
      - test_net

  mongo_test:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=nightfall_test
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - mongo_volume_test:/data/db
    networks:
      - test_net

  truffle-offchain_test:
    build:
      context: ./truffle
      dockerfile: Dockerfile
    environment:
      SOLC_VERSION: 0.5.8
      ETH_HOST: geth_test
      ETH_GAS: 6000000
      ETH_GAS_PRICE: 20000000000
    user: root
    volumes:
      - ./offchain/contracts:/home/node/truffle/contracts:delegated
      - ./offchain/migrations/:/home/node/truffle/migrations:delegated
      - ./offchain/build-test/contracts/:/home/node/truffle/build/contracts:cached
      - ./offchain/test/:/home/node/truffle/test:delegated
    depends_on:
      - geth_test
    logging:
      options:
        max-size: 10m
    networks:
      - test_net

  truffle-zkp_test:
    build:
      context: ./truffle
      dockerfile: Dockerfile
    environment:
      SOLC_VERSION: 0.5.8
      ETH_HOST: geth_test
      ETH_GAS: 6000000
      ETH_GAS_PRICE: 20000000000
    user: root
    volumes:
      - ./zkp/contracts/:/home/node/truffle/contracts:delegated
      - ./zkp/migrations/:/home/node/truffle/migrations:delegated
      - ./zkp/build-test/contracts/:/home/node/truffle/build/contracts:cached
      - ./zkp/test/:/home/node/truffle/test:delegated
      - ./zkp/src/:/home/node/truffle/src:delegated
    depends_on:
      - geth_test
    logging:
      options:
        max-size: 10m
    networks:
      - test_net

volumes:
  mongo_volume_test: {}
  zkp_code_test:
    driver: local
    driver_opts:
      type: none
      device: $PWD/zkp/code/
      o: bind

networks:
  test_net:
    driver: bridge
    ipam:
      driver: default
